language: node_js
node_js:
- '0.11'
- '0.12'
- '4.0'
- '5.0'
- '6.0'
sudo: false
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: jonno.haines@gmail.com
    api_key:
      secure: IjSqlNrFIB507wJM1IN54lmym0cvjd6V12W3U6pqFDy4Kfz9Rm781AD0gTL9T5VMZp8cbSteclXEGS2SuGbY7+O20mstPQJoTTxgHCIo/RePZElZNU8WQmE/vt0Phru38Qi5c0sKnvxDukiS5bmkK1Bivlu0KME01ObCM1TQ33iHhiNkjhCDm9PUcdW0EMcEwfuVfwHBBL1e8ZnHgadeS9wIsiqGueJkdJ3iChkqt3DrFN0zjI1YHju2MqoUV2XM7bu2VLmvUoGsRq18JRciLHw7eoJVR2uXA96QMYJR6qMB9DLyilbTETLveWFV5p/lL+i0ELVs02EnRNBJKWzKmYH/QIyXOJuVAHeN+m+4ucyuXMfJ5j78krHeVvpr5dXT3UBcAQgwLIG+aDv32gdxsUF4jAP45ZAcVv9cNaC+DmRuTN69e4yr22BYd3OtquYmapnW2YZ4q4OZ3f8BE1y8aK7K5mC+u0nIgc8z/DvitwLkOr8uYbZQtxL8rdNRXfKqIvRw49hsEzSxwspgYqdiACa58bW8lDymYednCE0/QwuI0wzVnCSwhCYJARe2ebyewZZ3TLGCOyWLylcl06L+6WvW3tn+yGu3Fi0pwprWRQZe+D745WuHD52KRx3rs3bxQ7gBT2LLIjcV74WWRcgRujWGg8oBbjfG3Et9Z//sjns=
    on:
      tags: true
      node: '6.0'
    skip_cleanup: true
    on:
      tags: true
      node: '6.0'
